### ISSUE TITLE
Sample checklists should all work in Docker

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/distributive#106]
As per issue #101 and PR #105, it is unexpected behavior when the sample checklists didn't work in the provided Dockerfile. We should make all samples work in this environment. This also provides another way to test Distributive before releases.

**Comment by nyanshak** [comment]
@siddharthist, I actually have a decent idea already of how to get this to (mostly) work. The only sample checks that I haven't gotten to work are the systemd checks in systemctl.json as gliderlabs/alpine:3.2 does not (as far as I can tell) support systemd. I can submit a PR for this if you'd like.

If so, there's two approaches I can take:
1) move systemctl.json to a separate location or add some sort of documentation saying that it doesn't work in the Dockerfile
2) move off of alpine to something else (ubuntu:{14.04, 14.10, 15.04, 15.10}, debian:jessie, etc)

Let me know if I can help out here.

**Comment by nyanshak** [comment]
Actually, wrt the issue about init systems, I think the problem is a bit harder than I first suspected. Maybe it would be better to make a (more) generic check for init systems by examining PID 1? I'm not sure.

**Comment by siddharthist** [comment]
@nyanshak Let's not worry about systemd checks right now, it'd be awesome if you could help with the other ones if you think it'd be easy enough!
