### ISSUE TITLE
Enable logging to disk

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/distributive#11]
Enable sending logs to disk:
 - [ ] Command line option to send all output to one file
 - [ ] JSON checklist option for where to log that checklist
 - [ ] JSON check option for where to log the output of that check

It must be 
 - [ ] Logstash compatible
 - [ ] Permissions concious

**Comment by tooda02** [comment]
This is already available in shipped-common/logging.  Method Logfile() provides the name of the file for collecting logging.  Collected logging includes TRACE logs even if they're suppressed from the console.  See shipped-bootstrap for an example of usage.

**Comment by siddharthist** [comment]
I can't find those repos. Could you link me to them? Additionally, we're trying to be framework-independent here in order to encourage wide usage, regardless of particulars. From the README.md: "Distributive attempts to be as framework-agnostic as possible."
