### ISSUE TITLE
Check for ulimit for root user

### ISSUE THREAD

**Issue by sehqlr** [CiscoCloud/distributive#115]
I was working on ciscocloud/microservices-infrastructure#775, and @stevendborrelli mentioned that we should add a check for this setting.

**Comment by siddharthist** [comment]
I don't know how feasible it is to check the number of open files for another user. It looks like `lsof` won't allow it if security mode is enabled [1]. I don't know of any other ways to list the number of open files. 

[1]: From [here](https://kb.acronis.com/sites/default/files/content/2010/02/8220/lsof.txt): If the symbol HASSECURITY is defined, a security mode is enabled,
and lsof will allow only the root user to list all open files.
Non-root users may list only open files whose processes have the
same user ID as the real user ID of the lsof process (the one that
its user logged on with).

**Comment by sehqlr** [comment]
I forgot that this was still active. Closing
