### ISSUE TITLE
responseMatchesInsecure (responseMatches w/o certificate verification)

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/distributive#39]
We should have an option to disable certificate validation when connection to a remote server to get a response. The solution is outlined [here](http://stackoverflow.com/questions/12122159/golang-how-to-do-a-https-request-with-bad-certificate).

**Comment by LeeLammert** [comment]
As distributive is only pulling check data, is there a drawback to not checking at all?

**Comment by siddharthist** [comment]
I think that there is no downside to having both, in case people want to be sure of the identity of the server that they're pulling the checklist from. Remember, checklists can run arbitrary code with `"command"`.

**Comment by siddharthist** [comment]
Fixed in 89046623f1e5c7663b88a319e118e1c4b512247a

**Comment by LeeLammert** [comment]
responseMatchesInsecure works great! In the near future, however, we will also need to handle authentication so actual returned data can be parsed.

**Comment by siddharthist** [comment]
See https://github.com/CiscoCloud/distributive/issues/43
