### ISSUE TITLE
how to get more recent rpms of distributive?

### ISSUE THREAD

**Issue by kbroughton** [CiscoCloud/distributive#77]
I'm using the MI ansible installer and it fails on the distributive call.
Cross linking to the issue there.

https://github.com/CiscoCloud/microservices-infrastructure/issues/686

**Comment by siddharthist** [comment]
Answered in CiscoCloud/microservices-infrastructure #686. Does that resolve your issue?

**Comment by kbroughton** [comment]
Yes, thanks.
