### ISSUE TITLE
make the package go-gettable

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/distributive#78]
Right now you can't `go get github.com/CiscoCloud/distributive`.

**Comment by siddharthist** [comment]
Ah shoot! This is a file organization problem that I'll fix right after I'm done with the refactoring work. Thanks for noticing!

**Comment by BrianHicks** [comment]
Would it be possible for me to fix separately? It's going to block
packaging. Lemme know, we can hop on a call to discuss if you like.

**Comment by siddharthist** [comment]
I'm happy to make this a priority and get a fix in soon.
