### ISSUE TITLE
Port not working if it's udp

### ISSUE THREAD

**Issue by orimarti** [CiscoCloud/distributive#81]
The "port" check works fine with TCP ports, but if I want to check if there is some listening UDP port it doesn't work. Maybe this should check /proc/net/udp too

**Comment by siddharthist** [comment]
Good thought! I'll work on this when I can, but if you'd like to put in a PR, I'd be happy to merge it. Look here for the relevant code: https://github.com/CiscoCloud/distributive/blob/master/workers/network.go#L18

**Comment by orimarti** [comment]
OK, I'll put in a PR when I'll have some time.  Thx!!

**Comment by orimarti** [comment]
Hey @siddharthist , I'm compiling the code but the resulting binary it's returning 0 in all cases. Is there any thing to take in consideration when compiling the code?

Thx!

**Comment by siddharthist** [comment]
Nope! I just use `go build`. I think you may be stumbling upon a separate bug... I'll try and track that one down today. Try using `--verbosity=info` to get relevant messages.

**Comment by siddharthist** [comment]
I found the issue, and have fixed it in my most recent commit to master :smile:

**Comment by orimarti** [comment]
Thanks!! :)

**Comment by orimarti** [comment]
PR done! :)

**Comment by siddharthist** [comment]
Closed by PR #85
